apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.ns }}
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.hostname }}
  dnsNames:
  - {{ .Values.hostname }}